-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'TASK_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'TASK_STATUS_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'GOAL_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'WORKSPACE_INVITED';
ALTER TYPE "NotificationType" ADD VALUE 'PROMOTED_TO_MANAGER';
ALTER TYPE "NotificationType" ADD VALUE 'REMOVED_FROM_WORKSPACE';
ALTER TYPE "NotificationType" ADD VALUE 'DEADLINE_REMINDER';
